
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <iostream>
#include "places.h"
#include "tries.h"
#include "airport.h"

list_airport_res *
listairport_1_svc(user_input *argp, struct svc_req *rqstp)
{
	name city, state;
	location loc;
	city = strdup(argp->city);
	state = strdup(argp->state);
	static list_airport_res  result;

    std::cout<<"Entering verymain";
		verymain();
    trieNode *pNode = (struct trieNode *) malloc(sizeof(struct trieNode));
    std::cout<<"Done with verymain!";
		fflush(stdout);
		char searchStr[100];
		strcpy(searchStr, argp->state);
		strcat(searchStr, argp->city);
    pNode = partialSearch(root->children, searchStr);
    std::cout<<"after  partial search";
		fflush(stdout);
		if (pNode != NULL)
		{
			std::cout<<pNode->longitude;
			std::cout<<pNode->latitude;
			std::cout<<pNode->entry;
			fflush(stdout);
		} else
		{
			std::cout<<"Partial search returned empty!";
			fflush(stdout);
			result.errno=1;
			return &result;
		}

	// 	CLIENT *clnt;
	// 	list_location_res  *result_1;
	// 	location  listlocation_1_arg;
	// 	char host[10];
	// 	strcpy(host,"localhost");
	//
	// #ifndef	DEBUG
	// 	clnt = clnt_create (host, LOCATIONPROG, LOCATIONVER, "udp");
	// 	if (clnt == NULL) {
	// 		clnt_pcreateerror (host);
	// 		exit (1);
	// 	}
	// #endif	/* DEBUG */
  // listlocation_1_arg.latitude = pNode->latitude;
	// listlocation_1_arg.longitude = pNode->longitude;
	//
	//
  //  result_1 = listlocation_1(&listlocation_1_arg, clnt);
	//  if (result_1 == (list_location_res *) NULL) {
 	// 	clnt_perror (clnt, "call failed");
	// 	result.errno=1;
	// 	return &result;
 	// }



	return &result;
}
