
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <iostream>
#include "places.h"
#include "tries.h"

list_airport_res *
listairport_1_svc(user_input *argp, struct svc_req *rqstp)
{
	name city, state;
	location loc;
	city = strdup(argp->city);
	state = strdup(argp->state);
	static list_airport_res  result;

    std::cout<<"Entering verymain";
		verymain();
    trieNode *pNode = (struct trieNode *) malloc(sizeof(struct trieNode));
    std::cout<<"Done with verymain!";
		fflush(stdout);
		char searchStr[100];
		strcpy(searchStr, argp->state);
		strcat(searchStr, argp->city);
    pNode = partialSearch(root->children, searchStr);
    std::cout<<"after  partial search";
		fflush(stdout);
		if (pNode != NULL)
		{
			std::cout<<pNode->longitude;
			std::cout<<pNode->latitude;
			fflush(stdout);
		} else
		{
			std::cout<<"Partial search returned empty!";
			fflush(stdout);
		}

	/*
	 * insert server code here
	 */

	return &result;
}
