/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airport.h"

list_location_res *
listlocation_1_svc(location *argp, struct svc_req *rqstp)
{
	static list_location_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}
